targets:
  - name: test
    args:
      env_type: non-prod
  - name: prod
    # You'll have to setup a kubeconfig context with the name `podtato-prod-cluster` to use this target
    # This will ensure that you never deploy this target to another cluster by accident.
    context: podtato-prod-cluster
    args:
      env_type: prod

args:
  - name: github_user
    default: "podtato-head"
  - name: github_token
    default: ""
  - name: image_name
    default: ghcr.io/podtato-head/podtato-server
  - name: image_version
    default: "v0.3.1"

discriminator: "podtato-head-{{ target.name }}"
