.PHONY: install
install:
	# TODO: Add your install logic here (installation of the delivery tool)

.PHONY: uninstall
uninstall:
	# TODO: Add your uninstall logic here

.PHONY: deploy-app
deploy-app:
	# TODO: Add your deploy-app logic here (podtato-head)

.PHONY: test
test: install deploy-app
	# TODO: Add your test logic here (podtato-head)
	make uninstall
