apiVersion: v1
kind: ServiceAccount
metadata:
  name: podtato-head
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: serviceaccount
{% if args.github_token != "" %}
imagePullSecrets:
  - name: ghcr
{% endif %}
