---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-{{ service.component }}
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: {{ service.component }}
spec:
  type: ClusterIP
  ports:
    - port: {{ service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: {{ service.component }}