apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podtato-kapp

resources:
  - https://github.com/podtato-head/podtato-head-app/releases/download/v0.3.1/manifest.yaml

images:
  - name: ghcr.io/podtato-head/podtato-server
    newTag: v0.3.3


